-- Skip demo service provider insertion
-- Users must sign up via auth first before they can be added to the users table
-- To create a service provider:
-- 1. Sign up via auth with email
-- 2. Update their role in the users table
-- 3. Insert into service_providers table 